export interface IUnitDetails{
    autoId : number;
    totalRecord : number;
    propertyNo : string;
    unitType : string;
    towerName : string;
    broucherDocument : string;
    communityName : string;
    developers : string;
    developerLogo : string;
    classificationName : string;
    purposeName : string;
    area : string;
    status : string;
    isActive : string;
    availablefrom : string;
    averageRent : string;
    bathroomType : string;
    bedroomType : string;
    builtUpSize : string;
    floor : string;
    furnishing : string;
    mapView : string;
    mortgageAvailability : string;
    ownthisfromjust : string;
    ownership : string;
    paymentPlan : string;
    plotsize : string;
    postedon : string;
    price : number;
    propertyAge : string;
    unitSize : string;
    serviceCharges : string;
    streetwidth : string;
    unitAvailable : string;
    usage : string;
    view : string;
    unitPageURL : string;
    unitDescription: string;
    unitTitle: string;
    unitMetaTitle: string;
    unitMetaDescription: string;
    contactSellerName: string;
    contactSellerDesignation: string;
    countryCodeContactSeller: string;
    contactSellerPhone: string;
    contactSellerEmail: string;
    contactSellerAvatar: string;
    firstUnitImagesPath: string;
}